app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::get('/thumb', function()
{

    $img = Image::make('test.jpg')->resize(300, 200);

    return $img->response('jpg');

});
Route::get('/admin', function()
{
	return Redirect::to('admin/category');
	return View::make('hello');
});
foreach(File::allFiles(__DIR__.'/routes/admin') as $route){

	require_once $route->getPathname();
}
foreach(File::allFiles(__DIR__.'/routes/front') as $route){

	require_once $route->getPathname();
}
// Route::get('/', function()
// {
// 	return Redirect::to('admin/category');
// 	return View::make('hello');
// });

app/models/Admin.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;


class Admin extends Base implements UserInterface, RemindableInterface  {

    use UserTrait;
    use RemindableTrait;

    protected $table = 'admins';

    public static $rules = array(
		'email'     => 'required|email',
    	'name'      => 'required|min:3',
		'password'  => 'required|min:6',
		'cpassword' => 'required|same:password',
	);
}

app/models/Attribute.php
<?php


class Attribute extends Base  {


	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
//	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');

	public function category()
    {
        return $this->belongsTo('Category');
    }

}

app/models/Base.php
<?php

class Base extends Eloquent
{

    public function fill(array $attributes)
     {
         foreach ($attributes as $key => $value)
         {
             $key = $this->removeTableFromKey($key);

             // The developers may choose to place some attributes in the "fillable"
             // array, which means only those attributes may be set through mass
             // assignment to the model, and all others will just be ignored.
             if ($this->isFillable($key))
             {
                 $this->setAttribute($key, $value);
             }
             elseif ($this->totallyGuarded())
              {
                  $this->setAttribute($key, $value);
                  // throw new MassAssignmentException($key);
             }
         }

         return $this;
     }

}

app/models/Brand.php
<?php


class Brand extends Base  {


	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');

}

app/models/Category.php
<?php


class Category extends Base  {


	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
//	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');


	public function attributes()
    {
        return $this->hasMany('Attributes');
    }

    public function getCategory($id){
    	$query = $this->whereId($id)->get();
    	return $query;
    }

}

app/models/Draft.php
<?php


class Draft extends Base  {


	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');

}

app/models/Inventory.php
<?php

class Inventory extends Base  {


	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
//	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');

	public function getStatus($pid){
		$query = $this->whereProduct_id($pid)->pluck('state');

		return $query;
	}

	public function getDate($pid){
		$query = $this->whereProduct_id($pid)->pluck('date');

		return $query;
	}

	public function getUnit($pid){
		$query = $this->whereProduct_id($pid)->pluck('unit');

		return $query;
	}

	public function getStock($pid){
		$query = $this->whereProduct_id($pid)->pluck('stock');

		return $query;
	}

}

app/models/Message.php
<?php


class Message extends Base  {

	protected $table = 'messages';

	public function owner($admin){
		if($admin == 1){
			return 'cd-timeline-block admin';
		}else{
			return 'cd-timeline-block';
		}
	}


	public function image($admin){
		if($admin == 1){
			return 'cd-timeline-img cd-admin';
		}else{
			return 'cd-timeline-img cd-user';
		}
	}

}

app/models/Order.php
<?php

class Order extends Base  {

	protected $table = 'orders';
	// protected $primary_key = "order_id";

	public function user()
	{
		return $this->belongsTo('User');
	}

	public function products()
	{
		return $this->hasMany('OrderProduct' , 'order_id');
	}

	public function order_status($status){
		if($status == 'Not Confirmed'){
			return "<span class='label label-danger'> $status </span>";
		}else if($status == 'Shipped'){
			return "<span class='label label-primary'> $status </span>";
		}else if($status == 'Cancelled'){
			return "<span class='label label-warning'> $status </span>";
		}else{
			return "<span class='label label-success'> $status </span>";
		}
	}


	public function is_deleted($id){
		$deleted =  User::whereId($id)->get()->first();
		if($deleted->is_deleted == 1){
			return "<span class='label label-danger'>Deleted</span>";;
		}else{
			return "<span class='label label-success'>Available</span>";;
		}
	}



}

app/models/OrderProduct.php
<?php


class OrderProduct extends Base  {

	protected $table = 'order_products';

	public function order()
	{
		return $this->belongsTo('Order');
	}

	public function product_details($id){
		return Product::whereId($id)->get()->first();
	}

	public function product_price($id , $qty){
		return Pricing::whereProduct_id($id)->where('quantity_from' , '<=' , $qty)->where('quantity_to' , '>=' , $qty)->pluck('price');
	}

	public function product_picture($id){
		return Picture::whereProduct_id($id)->whereMain(1)->get()->first();
	}
}

app/models/Picture.php
<?php


class Picture extends Base  {


	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
//	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');
    public function getProductImages($pid,$take= false){
        try{
           $qurry=  $this->whereProduct_id($pid)->whereMain(0);
            if($take){
                $qurry=$qurry->take();
            }
            $qurry = $qurry->get()->toArray();
        }catch (Exception $e){
            $qurry = array();
        }

        return $qurry;
    }

    public function getMainProductImage($pid){

        $query = $this->whereProduct_id($pid)->whereMain(1)->pluck('url');
        
        return (new Image())->resizeImage($query);
    }

    public function getSearchProductImage($pid){

        $query = $this->whereProduct_id($pid)->whereMain(1)->pluck('url');

        return $query;
    }

}

app/models/ProductAlternative.php
<?php

class ProductAlternative extends Base  {


	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'product_alternative';
	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');


}

app/controllers/Front/HomeController.php
<?php
namespace Front;
use DB;
use Attribute;
use BaseController;
use Category;
use Product;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\View;
// use Moltin\Cart\Facade\Cart;
use Input;
use Misc;
use Redirect;
use Validator;
use Route;
use Auth;
use User;
use Hash;
use Session;
use Cart;
use Pricing;
use Order;
use Picture;
use Inventory;
use OrderProduct;
use Shipping;
use UserFavorite;
use Brand;
use Omnipay\Omnipay;
use Setting;

class HomeController extends BaseController {

	/*
	|--------------------------------------------------------------------------
	| Default Home Controller
	|--------------------------------------------------------------------------
	|
	| You may wish to use controllers instead of, or in addition to, Closure
	| based routes. That's great! Here is an example controller method to
	| get you started. To route to this controller, just add the route:
	|
	|	Route::get('/', 'HomeController@showWelcome');
	|
	*/
	protected $data_for_view;

	// public function __construct()
 //    {
 //        // Fetch the Site Settings object
 //        // $this->site_settings = Setting::all();
 //    	$settings = Setting::first();
 //        $data_for_view['title'] = $settings->title;
 //        $data_for_view['phone'] = $settings->phone;
 //        View::share('title', $settings->title);
 //        View::share('phone', $settings->phone);
 //        if($settings->logo != ''){
 //        	View::share('logo', 'uploads/logo/'.$settings->logo);
 //        }else{
 //        	View::share('logo', 'ui-assets/assets/global/img/softbox_logo.png');
 //        }
 //    }

	public function getIndex() {
		// if(!Auth::check()){

		// }
		$data_for_view['categories'] = Category::whereParent('0')->wherePublish('1')->orderBy('order','desc')->get();
		$data_for_view['top_categories'] = Category::whereParent('0')->wherePublish('1')->get();
		$data_for_view['brands'] = Brand::all();
		$data_for_view['products'] = Product::all()->take(7);
		if(Auth::user()->check()){
			$data_for_view['favorites'] = UserFavorite::whereUser_id(Auth::user()->id())->get();
		}
		// dd(Auth::id());
		// dd($data_for_view);
		return View::make('front.masters.general',$data_for_view)->nest('content','front.models.list',$data_for_view);

	}

	public function getSearch(){
		$data_for_view['top_categories'] = Category::whereParent('0')->wherePublish('1')->get();
		$data_for_view['brands'] = Brand::all();
		$query = trim(Input::get('query'));
		$skip = 0;

		$product_count  = Product::where(function($quer) use ($query){
			$quer->where('title','like',"%$query%")->orWhere('code','like',"%$query%")->orWhere('description','like',"%$query%");
		})->whereStatus('1')->count();

		$results_products = Product::where('title','like',"%$query%")->orWhere('code','like',"%$query%")->orWhere('description','like',"%$query%")->paginate(8);
		$data_for_view['results_products'] = $results_products;
		$category_count =  Category::where(function($quer) use ($query){
			$quer->where('title','like',"%$query%")->orWhere('description','like',"%$query%");
		})->wherePublish('1')->count();
		$results_categories = Category::where(function($quer) use ($query){
			$quer->where('title','like',"%$query%")->orWhere('description','like',"%$query%");
		})->wherePublish('1')->paginate(8);
		$data_for_view['results_categories'] = $results_categories;
		$data_for_view['product_count']= $product_count;
		$data_for_view['category_count'] = $category_count;
		return View::make('front.masters.general',$data_for_view)->nest('content','front.models.search-results',$data_for_view);

	}



	public function getAddFavorite($cid){
		if(Auth::user()->check()){
			$uid = Auth::user()->id();
			$res = UserFavorite::whereUser_id($uid)->whereCategory_id($cid)->get();
			if(!$res->isEmpty()){
				return 2;
			}
			$favorites = array(
				'user_id' => $uid ,
				'category_id' => $cid
			);
			UserFavorite::create($favorites);
			return 1;
		}else{
			return 0;
		}

	}

	public function getDelFavorite($cid){
		$uid = Auth::user()->id();
		UserFavorite::whereUser_id($uid)->whereCategory_id($cid)->delete();
	}


	public function getShoppingCart() {
		$data_for_view['top_categories'] = Category::whereParent('0')->get();
		$data_for_view['brands'] = Brand::all();

		$data_for_view['categories'] = Category::whereParent('0')->get();
		$data_for_view['products'] = Product::all()->take(7);
		return View::make('front.masters.general',$data_for_view)->nest('content','front.models.shopping-cart',$data_for_view);

	}

	public function getRegister(){
		if(Auth::user()->check()){
			return Redirect::to('/');
		}
		$data_for_view['top_categories'] = Category::whereParent('0')->get();
		$data_for_view['brands'] = Brand::all();

		return View::make('front.masters.general',$data_for_view)->nest('content','front.models.register');
	}

	public function postRegister(){
		$user = new User;
		$user->first_name = Input::get('firstname');
		$user->last_name = Input::get('lastname');
		$user->telephone = Input::get('phone');
		$user->email = Input::get('email');
		$user->password = Hash::make(Input::get('password'));
		$user->save();


		if(Auth::user()->attempt(array('email'=>Input::get('email'), 'password'=>Input::get('password')))){
			Session::put('email' , Input::get('email'));
			$id = User::whereEmail(Input::get('email'))->get()->first()->id;
			Session::put('id' , $id);

			if(Session::has('prev_url')){
				return Redirect::to(Session::get('prev_url'))->with('messagee', 'You Are Now Logged In');
			}

			return Redirect::to('/')->with('messagee', 'You Are Now Logged In');
		}

		return Redirect::to('/')->with('messagee', 'Thanks for registering!');
	}

	public function getLogin(){
		if(Auth::user()->check()){
			return Redirect::to('/');
		}
		$data_for_view['top_categories'] = Category::whereParent('0')->get();
		$data_for_view['brands'] = Brand::all();

		return View::make('front.masters.general',$data_for_view)->nest('content','front.models.login');
	}

	public function postLogin(){
		// dd(Auth::user()->attempt(array('email'=>Input::get('email'), 'password'=>Input::get('password'))));
		if(Auth::user()->attempt(array('email'=>Input::get('email'), 'password'=>Input::get('password')))){
			Session::put('email' , Input::get('email'));
			$id = User::whereEmail(Input::get('email'))->get()->first()->id;
			Session::put('id' , $id);

			// if(Session::has('prev_url')){
			// 	return Redirect::to(Session::get('prev_url'))->with('messagee', 'You Are Now Logged In');
			// }

			return Redirect::back()->with('messagee', 'You Are Now Logged In');
		}else{
			return Redirect::back()->with('errorMsg','Error: Wrong Email or password combination!');
			// return Redirect::to('/login')->with('errorMsg', '');
		}
	}

	public function getCart($id){
		$product = Product::whereId($id)->get()->toArray();
		// dd($product);
		Cart::add($id,$product[0]['title'],1,500);
		// dd("done");
		return Redirect::back();
	}

	public function getAddCart(){
		$pid = Input::get('pid');
		$qty = Input::get('qty');
		$out_of_stock = 0;
		$remaining = 0;
		$available = Inventory::whereProduct_id($pid)->pluck('stock');
		// check if the product already exists or not
		$result = Cart::search(array('id'=>$pid));

		//update quantity if product exist in cart
		if($result){
			$prev_qty = Cart::get($result[0])->qty;
			$qty = $qty + $prev_qty;
		}


		if($qty > Inventory::whereProduct_id($pid)->pluck('stock')){
			$qty = Inventory::whereProduct_id($pid)->pluck('stock');
			$out_of_stock = 1;
			$remaining = Input::get('qty') - $qty;
		}


		//get price for quantity qty
		$product = Product::whereId($pid)->get()->toArray();
		if($qty > Pricing::whereProduct_id($pid)->max('quantity_to')){
			$max = Pricing::whereProduct_id($pid)->max('quantity_to');
			$price   = Pricing::whereProduct_id($pid)->whereQuantity_to($max)->pluck('price');

			$prom = Pricing::whereProduct_id($pid)->whereQuantity_to($max)->get();
			if($prom[0]->pormotions_type=="$"){
				$price = $price - ($prom[0]->pormotions);
			}elseif($prom[0]->pormotions_type=="%"){
				$perc = $prom[0]->pormotions / 100 ;
				$price = $price - ($price * $perc);
			}
		}else{
			$price = Pricing::whereProduct_id($pid)->where('quantity_from','<=',$qty)->where('quantity_to','>=',$qty)->pluck('price');

			$prom = Pricing::whereProduct_id($pid)->where('quantity_from','<=',$qty)->where('quantity_to','>=',$qty)->get();
			if($prom[0]->pormotions_type=="$"){
				$price = $price - ($prom[0]->pormotions);
			}elseif($prom[0]->pormotions_type=="%"){
				$perc = $prom[0]->pormotions / 100 ;
				$price = $price - ($price * $perc);
			}
		}

		//other options uom , image , and code
		$code = Product::whereId($pid)->pluck('code');
		$image = Picture::whereProduct_id($pid)->whereMain('1')->pluck('url');
		if($image==null){
			$image = Picture::whereProduct_id($pid)->pluck('url');
		}
		$uom = Inventory::whereProduct_id($pid)->pluck('unit');

		//add new or update existing
		if($result){
			Cart::update($result[0],array('qty'=>$qty,'price'=>$price));
		}else{
			Cart::add($pid,$product[0]['title'],$qty,$price, array('uom' => $uom , 'image' => $image , 'code' => $code));
		}

		return json_encode([$out_of_stock,$available,$remaining]);

	}

	public function getCartContent(){

		return View::make('front.models.cart-content');
	}

	public function getCartRemove(){

		$rowid = Input::get('rowid');
		try{
			Cart::remove($rowid);
		}catch(Exception $e){

		}
		if(Cart::count()==0){
			return json_encode([0]);
		}
		return json_encode([1,Cart::total()]);
	}


	public function getEdit(){

		$id  = Input::get('id');
		$qty = Input::get('qty');
		$result   = Cart::search(array('rowid' => $id));

		Cart::update($result[0],array('qty' => $qty));

		return Cart::total();
	}


	public function getCheckout(){
		$data_for_view['top_categories'] = Category::whereParent('0')->get();
		$data_for_view['brands'] = Brand::all();
		Session::set('prev_url',Route::getCurrentRoute()->getPath());
		if(Auth::user()->check()){

app/views/admin/models/users/users.blade.php
@extends('admin.layouts.main')

@section('content')

@include('admin.layouts.sidebar')
<!-- END SIDEBAR -->
<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
  <div class="page-content">
    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
    <!-- /.modal -->
    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->

    <!-- BEGIN PAGE HEADER-->
    @include('admin.layouts.page_header')

    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div class="row">

      <form role="form" name="general_user" id="general_user" action="{{ URL::route('admin.users.index') }}">
      </form>
      <form role="form" name="general_order" id="general_order" action="{{ URL::route('admin.orders.index') }}">
      </form>
      <form role="form" name="messages" id="messages" action="{{ URL::route('messages') }}">
      <input type="hidden" id="ticket_id" value="">

      <form id="profile_form" method="POST" action="{{ URL::route('profile') }}">
      </form>
      <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
      <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
              <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
              Widget settings form goes here
            </div>
            <div class="modal-footer">
              <button type="button" class="btn blue">Save changes</button>
              <button type="button" class="btn default" data-dismiss="modal">Close</button>
            </div>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.modal -->
      <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->


      <div id="message" style="display:none;"></div>



      <!-- Users Tabel-->
      <div id="Users_table">
        <div class="col-md-12">
          <div>
            <!-- Content Table -->
            <div class="row">
              <div class="col-md-12">
                <!-- Begin: life time stats -->
                <div class="portlet light">
                  <div class="portlet-title">
                    <div class="caption">
                      <i class="icon-basket font-green-sharp"></i>
                      <span class="caption-subject font-green-sharp bold uppercase">Users Listing</span>
                    </div>

                    <div class="actions" style="width:25%">
                      <div class="input-group" style="width:90%">
                        <input type="text" class="form-control"  onkeydown="if (event.keyCode == 13){filter_user(this.value)}" placeholder="Name - Email - Telephone">
                      </div>
                    </div>



              </div>


              <div class="portlet-body">
                <div class="table-scrollable">
                  <table class="table table-striped table-bordered table-hover" id="datatable_orders">
                    <thead>
                      <tr role="row" class="heading">
                        <th width="5%">
                          #
                        </th>
                        <th width="10%">
                          First Name
                        </th>
                        <th width="10%">
                          Last Name
                        </th>
                        <th width="20%">
                          E-mail
                        </th>
                        <th width="10%">
                          Telephone
                        </th>
                        <th>
                          Available
                        </th>
                        <th width="20%">
                          Join On
                        </th>
                        <th width="25%">
                          Actions
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($users as $user)
                      <tr role="row" class="odd">
                        <td> {{ $user->id }} </td>
                        <td>{{ $user->first_name }} </td>
                        <td>{{ $user->last_name }} </td>
                        <td>{{ $user->email }} </td>
                        <td>{{ $user->telephone }} </td>
                        <td>{{ $user->is_deleted($user->id) }} </td>
                        <td> {{ date('F d, Y', strtotime($user->created_at)) }} </td>
                        <td>
                          <ul class="list-inline text-center">
                            <li>
                                <a onclick="showUser({{ $user->id }})" href="#" class="btn btn-xs blue">View<i class="fa fa-list"></i></a>
                              </li>
                              <li>
                                <a onclick="delete_box('{{ $user->first_name . ' ' . $user->last_name}}' , {{ $user->id }})" href="#" class="btn btn-xs red">Delete <i class="fa fa-close"></i></a>
                              </li>

                            </ul>
                          </td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
              <!-- End: life time stats -->
            </div>
          </div>
          <!-- Content Table -->
        </div>
      </div>
    </div>
    <!-- Users Tabel-->

    <!-- View User-->
    <div id="view_user" style="display:none;">
    </div>
    <!-- View User-->


    <div id="delete_box" style="display:none;">
      <div class="col-md-12">
        <form action="{{ URL::route('admin.users.destroy') }}" id="delete_form">
          <div class="bs-callout bs-callout-warning" id="callout-fieldset-disabled-pointer-events">
            <p> <span id="confirm_message"></span> </p>
            <div style="margin-top:20px;">
              <a href="javascript:;" class="btn green-haze" id="deleteBtn">
                Delete </a>
                <a href="javascript:;" class="btn default" onclick="back_to_table('users')">
                  Cancel </a>
                </div>
              </div>
            </form>
          </div>
        </div>


      </div>
      <!-- END PAGE CONTENT-->
    </div>
  </div>
  <!-- END CONTENT -->
  <!-- BEGIN QUICK SIDEBAR -->
  <!--Cooming Soon...-->
  <!-- END QUICK SIDEBAR -->
  <!---->
  @stop

  <!---->



  @section('script.footer')

  <style type="text/css">
  th,td{
    text-align:center;
  }
  </style>

  @stop

app/views/admin/models/users/users_table.blade.php
<div class="col-md-12">
  <div>
    <!-- Content Table -->
    <div class="row">
      <div class="col-md-12">
        <!-- Begin: life time stats -->
        <div class="portlet light">
          <div class="portlet-title">
            <div class="caption">
              <i class="icon-basket font-green-sharp"></i>
              <span class="caption-subject font-green-sharp bold uppercase">Users Listing</span>
            </div>

            <div class="actions" style="width:25%">
              <div class="input-group" style="width:90%">
                <input value="{{ $value }}" type="text" class="form-control"  onkeydown="if (event.keyCode == 13){filter_user(this.value)}" placeholder="Name - Email - Telephone" value="{{ $value }}">
              </div>
            </div>

          </div>


          <div class="portlet-body">
            <div class="table-scrollable">
                <table class="table table-striped table-bordered table-hover" id="datatable_orders">
                  <thead>
                    <tr role="row" class="heading">
                      <th width="5%">
                        #
                      </th>
                      <th width="10%">
                        First Name
                      </th>
                      <th width="10%">
                        Last Name
                      </th>
                      <th width="20%">
                        E-mail
                      </th>
                      <th width="10%">
                        Telephone
                      </th>
                      <th>
                        Available
                      </th>
                      <th width="20%">
                        Join On
                      </th>
                      <th width="25%">
                        Actions
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($users as $user)
                    <tr role="row" class="odd">
                      <td> {{ $user->id }} </td>
                      <td>{{ $user->first_name }} </td>
                      <td>{{ $user->last_name }} </td>
                      <td>{{ $user->email }} </td>
                      <td>{{ $user->telephone }} </td>
                      <td>{{ $user->is_deleted($user->id) }} </td>
                      <td> {{ date('F d, Y', strtotime($user->created_at)) }} </td>
                      <td>
                        <ul class="list-inline text-center">
                          <li>
                              <a onclick="showUser({{ $user->id }})" href="#" class="btn btn-xs blue">View<i class="fa fa-list"></i></a>
                            </li>
                            <li>
                              <a onclick="delete_box('{{ $user->first_name . ' ' . $user->last_name}}' , {{ $user->id }})" href="#" class="btn btn-xs red">Delete <i class="fa fa-close"></i></a>
                            </li>

                          </ul>
                        </td>
                      </tr>
                      @endforeach
                    </tbody>
                  </table>
            </div>
          </div>
        </div>
        <!-- End: life time stats -->
      </div>
    </div>
    <!-- Content Table -->
  </div>
</div>